### ISSUE TITLE
License

### ISSUE THREAD

**Issue by freefri** [valnub/Framework7-Pure-Angular-Template#10]
Hello, 
could you add a license to your project so we know the conditions of forking it?
e.g MIT https://github.com/nolimits4web/Framework7/blob/master/LICENSE or Apache https://github.com/apache/cordova-android/blob/master/LICENSE

Thank you

**Comment by valnub** [comment]
It's done :-)

https://github.com/valnub/Framework7-Pure-Angular-Template/blob/master/LICENSE
