### ISSUE TITLE
ng-include route error

### ISSUE THREAD

**Issue by Leitonez** [valnub/Framework7-Pure-Angular-Template#12]
Hi, guys.
I am using Framework7 with Angular.js and everything works fine. But when I try to use ng-include in one of my pages, my app get broken. I realized that url becomes wrong.
Before I call the page which has ng-include, my route is:
app/view/index.html#!/menu.html (and it's OK)
After my page with ng-include load, I got the follow url:
app/view/index.html#/!/requestcategories.html (with a slash between #! – which seems wrong)
My code:

```
<script type=“text/ng-template” id=“recursiveitem”>
<span>Test</span>
</script>

<div data-ng-include=“'recursive_item'”></div>
```
Could you help me?
Thank you!

**Comment by valnub** [comment]
Hi Leitonez, please read this post about F7 + Angular: https://www.timo-ernst.net/blog/2017/02/08/using-angular-with-framework7-in-2017/
