### ISSUE TITLE
It's seems to don't work

### ISSUE THREAD

**Issue by Simone-cogno** [valnub/Framework7-Pure-Angular-Template#2]
I have just upload this on my website but it's white page with a text hello world and nothing else. I have to do some other configurations?

**Comment by valnub** [comment]
- Check console logs. Any javascript errors?
- Check network log. Any 404s?

**Comment by valnub** [comment]
I just checked and if you see a white page with "hello world" then everything is ok. Remember: This is just a **template**. You have to fill it with what ever content or UI components you like.

**Comment by Simone-cogno** [comment]
Yes I have:
Viewport argument key "minimal-ui" not recognized and ignored.
Failed to load resource: the server responded with a status of 404 (Not Found) angular.min.js.map

**Comment by Simone-cogno** [comment]
Ah ok sorry, I though it was the movie template example

**Comment by valnub** [comment]
Oh, nope. This is just an empty template :-)
You can find the demo here: https://github.com/valnub/Framework7-with-AngularJS-demo-app
