### ISSUE TITLE
ng-repeat doesn't work on device

### ISSUE THREAD

**Issue by fhbash** [valnub/Framework7-Pure-Angular-Template#3]
Hi.. I follow these tutorial, but in my html, when I use ng-repeat.. in android or iOS doesn't work, doesn't render the HTML...

Any tips for these?

**Comment by valnub** [comment]
Can you be a bit more precise? Any Javascript errors? What changes did you do?
Since I don't know your code I can't tell what's wrong. Left my magic crystal sphere at home.

**Comment by fellipeh** [comment]
Hi @valnub , thanks for your response..

My problem is, when I try to get json using ajax, this error appears:

```
XMLHttpRequest cannot load http://local.soofertas.net.br:8000/api/v1/destaques. Response for preflight is invalid (redirect)
```

I try in chrome, safari, Iphone and Android.. doesn't show anything... but in my computer using Firefox works fine..

Any ideia what is going on?

Thanks!

**Comment by fhbash** [comment]
Hi @valnub ,

My problem is.. when I try using Chrome in my desktop works fine...  but using my Device... doesn't call the REST API... read all HTML, but doesn't call my json address... in desktop the json address is called after open all files in html... but in my devices, nothing...

When I try to open in other computer, same error occours... in other words, works fine in my computer.. if I need to access in other computer/device, doesn't call the json listener..

Cheers

**Comment by valnub** [comment]
Can you post me a link so I can see it?

**Comment by valnub** [comment]
Do you still need help or can I close this ticket?

**Comment by fhbash** [comment]
No, I don't still need help, thanks!
