### ISSUE TITLE
How can I use angular on ajax loaded pages?

### ISSUE THREAD

**Issue by YagoLopez** [valnub/Framework7-Pure-Angular-Template#4]
Hello. Excuse my English, I'm from Spain.

I can use angular controllers within inline pages.  I'm trying to load a page using ajax but I can't use an angular controller defined for that page. I think it is logic because the page is not loaded in dom.

Do you know any way to use angular within ajax loaded pages in F7?

Thanks.

**Comment by valnub** [comment]
Hi Yago,
I usually do not use injected dom pages with F7, thus I cannot help on this matter. Instead, I recommend to ask on F7 forums or Stackoverflow.
- http://www.idangero.us/framework7/forum/
- http://www.stackoverflow.com

If you ask on one of these platforms, could you please post a backlink to the question here since I am interested in a solution, thanks :)

**Comment by YagoLopez** [comment]
Ok, thank you very much. I'll ask in that places. If I get any news I'll let you know. By the way, I will like to use cordova too in my project. I'm new to Framerowk 7, came from using Ionic. Is there any way to use cordova-phonegap?

**Comment by valnub** [comment]
Sure, cordova works fine with F7

**Comment by YagoLopez** [comment]
How is it done? installing cordova npm plugin from command line at the directory project maybe?

**Comment by valnub** [comment]
https://cordova.apache.org/docs/en/5.4.0/guide/cli/index.html

**Comment by YagoLopez** [comment]
Ok, i'll take a look. chao :)

**Comment by valnub** [comment]
I created a blog post about this in case you still have this issue: http://www.timo-ernst.net/blog/2016/02/24/how-to-use-ajax-pages-with-angular-1-x-in-framework7/

**Comment by YagoLopez** [comment]
Wow, thanks Timo. A very elegant and simple solution. I was using ng-include to load html templates in my F7+angular project. Not exactly what I wanted. This way is much better. I have left you a comment with a question in your blog. Answer there if you want. Cheers!
