### ISSUE TITLE
Framework7 seperate page with Angularjs

### ISSUE THREAD

**Issue by vaibhavch** [valnub/Framework7-Pure-Angular-Template#5]
All the controllers reside in index.html in your template. How can we deal when there is another page other than index.html like in framework7 maintains seperate pages in app. As seperate pages dynamically update in index.html.  I have already tried many tweaks like 

```
  myApp.app.onPageInit('otherpage', function (page) {

  'Shoper.angular.controller('otherPageController', ['$scope', '$http', 'InitService', function           ($scope, $http, InitService) {
   'use strict';

    InitService.addEventListener('ready', function () {
           // DOM ready

        });

       }]);

        });
```

Please help with this scenerio. Thanks!

**Comment by valnub** [comment]
Hi, I usually do not split my app into multiple pages, instead I put everything into index.html to keep number of HTTP request to a minimum.

If you need help with this, I recommend to ask on F7 forums: http://www.idangero.us/framework7/forum/

**Comment by ztl8702** [comment]
You may use `<ng-include>`. But you have to put a wrapper for each page in index.html.

It is fine to have multiple HTTP requests if using Cordova. And separating into multiple pages also helps collaboration.

**Comment by valnub** [comment]
You're right about cordova, for browser-based applications this is something I would keep in mind though.

For organization purposes you can also split into multiple files and put em together using a grunt/gulp task. No need to use angular.

**Comment by valnub** [comment]
I created a blog post about this in case you still have this issue: http://www.timo-ernst.net/blog/2016/02/24/how-to-use-ajax-pages-with-angular-1-x-in-framework7/
