### ISSUE TITLE
Not working in device

### ISSUE THREAD

**Issue by ashokkumar88** [valnub/Framework7-Pure-Angular-Template#8]
Hi,
The blank template is working fine in local server. but when building it with cordova, the html is rendering but when I am clicking on any link nothing happens. No error in console.

**Comment by valnub** [comment]
Hey, you have to make 100% sure that Cordova's "deviceready" event is fired. If it doesn't the template/app won't work.
Usually this is a problem if cordova.js is not properly included in html, so double check if you added this manually:

``` javascript
<script type="text/javascript" src="cordova.js"></script>
```

**Comment by ashokkumar88** [comment]
omg! I forgot to add cordova.js. It is working fine now. Thanks very much valnub. You saved my day.

**Comment by ashokkumar88** [comment]
should I assign the $scope variables this way?

```
MyApp.angular.controller('DetailPageController', ['$scope', '$http', 'InitService', function ($scope, $http, InitService) {
  'use strict';

  InitService.addEventListener('ready', function () {
    // DOM ready
    console.log('DetailPageController: ok, DOM ready');
    $scope.test = 'testing';
    // You can access angular like this:
    // MyApp.angular

    // And you can access Framework7 like this:
    // MyApp.fw7.app
  });

}]);
```

**Comment by valnub** [comment]
Yeah, looks good

**Comment by ashokkumar88** [comment]
But the $scope value is not showing in the view.

**Comment by valnub** [comment]
You need to set scope variables outside of the ready function:

``` javascript
MyApp.angular.controller('DetailPageController', ['$scope', '$http', 'InitService', function ($scope, $http, InitService) {
  'use strict';

  $scope.test = 'testing';

  InitService.addEventListener('ready', function () {
    // DOM ready
    console.log('DetailPageController: ok, DOM ready');
    // You can access angular like this:
    // MyApp.angular

    // And you can access Framework7 like this:
    // MyApp.fw7.app
  });

}]);
```

**Comment by ashokkumar88** [comment]
yeah! working fine. Thanks a lot.

**Comment by valnub** [comment]
You're welcome :)

**Comment by ashokkumar88** [comment]
I have almost completed a app using Onsen UI. Now I am thinking to switch to F7. Do you think that using F7 with Angular degrade the performance compare to without Angular?

**Comment by valnub** [comment]
Possible but not certain. Angular is not very well known for its performance. I don't know about Angular2 though, you might want to look into that.

**Comment by ashokkumar88** [comment]
ok. thanks
